name: net2o # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.9.7-20200319' # just for humans, typically '1.2+git' or '1.3.2'
summary: net2o snap # 79 char long summary
description: |
  This is the weekly development snapshot of net2o in snap format.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
type: app
license: AGPL-3.0+ # SPDX 2.0 identifiers

apps:
  gforth-fast:
    command: bin/gforth-fast
    environment:
      GFORTHPATH: .:/snap/net2o/current/usr/lib/x86_64-linux-gnu/gforth/0.7.9_20200305:/snap/net2o/current/usr/share/gforth/0.7.9_20200305:/snap/net2o/current/usr/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/net2o/current/usr/lib/x86_64-linux-gnu/gforth/0.7.9_20200305/amd64/libcc-named
      GFORTHFONTS: /snap/net2o/current/usr/share/fonts/
      LIBGL_DRIVERS_PATH: /snap/net2o/current/usr/lib/x86_64-linux-gnu/dri
      GFORTH_GL: glx
    plugs:
      - home
      - network
      - netlink-connector
      - x11
      - opengl
      - unity7
  gforth:
    command: bin/gforth
    environment:
      GFORTHPATH: .:/snap/net2o/current/usr/lib/x86_64-linux-gnu/gforth/0.7.9_20200305:/snap/net2o/current/usr/share/gforth/0.7.9_20200305:/snap/net2o/current/usr/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/net2o/current/usr/lib/x86_64-linux-gnu/gforth/0.7.9_20200305/amd64/libcc-named
      GFORTHFONTS: /snap/net2o/current/usr/share/fonts/
      LIBGL_DRIVERS_PATH: /snap/net2o/current/usr/lib/x86_64-linux-gnu/dri
      GFORTH_GL: glx
    plugs:
      - home
      - network
      - netlink-connector
      - x11
      - opengl
      - unity7
  n2o:
    command: bin/gforth-fast /snap/net2o/current/bin/n2o
    environment:
      GFORTHPATH: .:/snap/net2o/current/usr/lib/x86_64-linux-gnu/gforth/0.7.9_20200305:/snap/net2o/current/usr/share/gforth/0.7.9_20200305:/snap/net2o/current/share/gforth/0.7.9_20200305/net2o:/snap/net2o/current/usr/share/gforth/site-forth:~+
      GFORTHCCPATH: /snap/net2o/current/usr/lib/x86_64-linux-gnu/gforth/0.7.9_20200305/amd64/libcc-named:/snap/net2o/current/lib/gforth/0.7.9_20200305/amd64/libcc-named
      GFORTHFONTS: /snap/net2o/current/usr/share/fonts/
      LIBGL_DRIVERS_PATH: /snap/net2o/current/usr/lib/x86_64-linux-gnu/dri
      GFORTH_GL: glx
    plugs:
      - home
      - network
      - netlink-connector
      - x11
      - opengl
      - unity7

parts:
  prepare:
    plugin: nil
    override-pull: |
      echo "deb [arch=i386,amd64,armhf,armel,arm64,powerpc,mips,mipsel,all] https://net2o.de/debian testing main" >/etc/apt/sources.list.d/net2o.list
      wget -O - https://net2o.de/bernd@net2o.de-yubikey.pgp.asc | apt-key add -
      apt update
    prime: [-*]
    build-packages:
      - software-properties-common
      - dirmngr
  desktop-glib-only:
    source: .
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
  net2o:
    source: https://git.net2o.de/bernd/net2o.git
    source-tag: 0.9.7-20200319
    plugin: autotools
    configflags:
      - --disable-gps
    after:
      - prepare
      - desktop-glib-only
    build-packages:
      - libtool-bin
      - libgps-dev
      - libffi-dev
      - gforth-minos2
    stage-packages:
      - libltdl7
      - libfreetype6
      - libglvnd0
      - libglx0
      - libpng16-16
      - libvulkan1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libegl1-mesa
      - libgles2-mesa
      - libgl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxrandr2
      - libxrender1
      - fonts-noto
      - fonts-liberation
      - fonts-arphic-gkai00mp
      - fonts-noto-emoji
      - fonts-awesome
      - libsoil2
      - freetype-gl
      - gforth-minos2
      - libgps-dev
